apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tstr
spec:
  ingressClassName: caddy
  rules:
    - host: api.demo.tstr.dev
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: tstr-api
              port:
                number: 9000
    - host: demo.tstr.dev
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: tstr-ui
              port:
                number: 8000
