apiVersion: v1
kind: Service
metadata:
  name: tstr-api
  labels:
    app: tstr-api
spec:
  ports:
  - port: 9000
    targetPort: api
    protocol: TCP
  selector:
    app: tstr-api
---
apiVersion: v1
kind: Service
metadata:
  name: tstr-ui
  labels:
    app: tstr-ui
spec:
  ports:
  - port: 8000
    targetPort: ui
    protocol: TCP
  selector:
    app: tstr-ui
