apiVersion: v1
kind: Service
metadata:
  name: tstr-grpc
  labels:
    app: tstr-grpc
spec:
  ports:
  - port: 9000
    targetPort: grpc
    protocol: TCP
  selector:
    app: tstr
---
apiVersion: v1
kind: Service
metadata:
  name: tstr-json
  labels:
    app: tstr-json
spec:
  ports:
  - port: 9090
    targetPort: json
    protocol: TCP
  selector:
    app: tstr
---
apiVersion: v1
kind: Service
metadata:
  name: tstr-ui
  labels:
    app: tstr-ui
spec:
  ports:
  - port: 8000
    targetPort: ui
    protocol: TCP
  selector:
    app: tstr
