name: Build
on:
  workflow_call:
    outputs:
      image_tag:
        description: The tag for the built and pushed image
        value: ${{ jobs.build-and-push-image.outputs.image_tag }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v10
        with:
          name: tstr
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build container image
        id: build
        run: |
          nix build .#image
          echo "::set-output name=image_tag::$(nix eval --raw .#image.imageTag)"
      - name: Load container image
        run: "docker load < result"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: nanzhong
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Push container image
        run: |
          docker push "nanzhong/tstr:${{ steps.build.outputs.image_tag }}"
