name: Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v10
        with:
          name: tstr
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build container image
        run: |
          nix build .#image
          echo image_tag="$(nix eval .#image.imageTag)" >> $GITHUB_ENV
      - name: Load container image
        run: "docker load < result"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: nanzhong
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Push container image
        run: docker push "nanzhong/tstr:${{ env.image_tag }}"
