name: Test
on:
  pull_request:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - uses: cachix/cachix-action@v10
        with:
          name: tstr
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Run go tests
        run: nix develop -c go test ./...
